// RSI Status page integration.
//
// status.robertsspaceindustries.com publishes its state in three machine-
// readable forms: HTML, RSS (/index.xml) and JSON (/index.json). We use the
// JSON one — it exposes exactly the shape we need (overall summary status,
// per-system status, unresolved incidents) without the parsing cost of RSS.
//
// The feed is generated by cState (cstate.github.io), so the schema is
// documented + stable. A field can be empty when cState templates leave it
// blank, so the Zod shape defaults everything optional.

import { z } from 'zod';
import { RSI_STATUS_BASE_URL } from '../constants.js';
import { fetchWithTimeout } from '../net.js';

/**
 * cState status vocabulary. Mirrors the tokens emitted by the JSON feed's
 * `summaryStatus` and per-system `status` fields.
 *   operational  — everything green
 *   notice       — informational, no impact on services
 *   disrupted    — partial or intermittent impact
 *   down         — full outage of at least one system
 *   maintenance  — scheduled downtime in progress
 */
export const RSI_STATUS_LEVELS = ['operational', 'notice', 'disrupted', 'down', 'maintenance'] as const;
export type RsiStatusLevel = (typeof RSI_STATUS_LEVELS)[number];

// Sort order by severity so callers can pick a "worst system" when the
// overall summary is missing or out of sync with per-system states.
const LEVEL_SEVERITY: Record<RsiStatusLevel, number> = {
  operational: 0,
  notice: 1,
  maintenance: 2,
  disrupted: 3,
  down: 4,
};

function coerceLevel(v: unknown): RsiStatusLevel {
  if (typeof v === 'string' && (RSI_STATUS_LEVELS as readonly string[]).includes(v)) {
    return v as RsiStatusLevel;
  }
  // Unknown / missing: treat as operational. The pill won't scare users
  // if the remote schema adds a new token we don't recognize.
  return 'operational';
}

const RawUnresolvedIssue = z
  .object({
    title: z.string().default(''),
    link: z.string().default(''),
    informational: z.boolean().optional(),
    severity: z.string().optional(),
  })
  .passthrough();

const RawSystem = z
  .object({
    name: z.string().default(''),
    category: z.string().default(''),
    status: z.string().default('operational'),
    unresolvedIssues: z.array(RawUnresolvedIssue).default([]),
  })
  .passthrough();

const StatusResponse = z
  .object({
    summaryStatus: z.string().default('operational'),
    systems: z.array(RawSystem).default([]),
    buildDate: z.string().default(''),
    buildTime: z.string().default(''),
    buildTimezone: z.string().default('UTC'),
  })
  .passthrough();

export interface RsiStatusUnresolvedIssue {
  title: string;
  url: string;
  informational: boolean;
}

export interface RsiStatusSystem {
  name: string;
  category: string;
  level: RsiStatusLevel;
  unresolvedIssues: RsiStatusUnresolvedIssue[];
}

export interface RsiStatusSummary {
  /** Overall level, derived from `summaryStatus` when present, else the
   *  worst per-system level. */
  level: RsiStatusLevel;
  /** Raw `summaryStatus` value (if different from `level`, we took the
   *  worse per-system level to be safe). */
  reportedLevel: RsiStatusLevel;
  systems: RsiStatusSystem[];
  /** Every unresolved issue across all systems, de-duped by title+url. Most
   *  users only care about the aggregate — not which system has it. */
  unresolvedIssues: RsiStatusUnresolvedIssue[];
  /** UTC timestamp the status feed was generated (ISO-ish). Empty when
   *  cState didn't emit the fields, which happens on local previews. */
  generatedAt: string;
  /** URL to the human-facing status page so the popup can link users out
   *  when they want more detail. */
  pageUrl: string;
}

export async function fetchRsiStatus(): Promise<RsiStatusSummary> {
  const response = await fetchWithTimeout(`${RSI_STATUS_BASE_URL}/index.json`, {
    credentials: 'omit',
    headers: { Accept: 'application/json' },
  });
  if (!response.ok) {
    throw new Error(`rsi status returned ${response.status}`);
  }
  const raw = (await response.json()) as unknown;
  const parsed = StatusResponse.parse(raw);

  const systems: RsiStatusSystem[] = parsed.systems.map((s) => ({
    name: s.name,
    category: s.category,
    level: coerceLevel(s.status),
    unresolvedIssues: s.unresolvedIssues.map((i) => ({
      title: i.title || 'Unresolved incident',
      url: i.link || `${RSI_STATUS_BASE_URL}/`,
      informational: Boolean(i.informational),
    })),
  }));

  // Aggregate unresolved issues across systems, de-duped — when one incident
  // hits multiple systems cState reports it on each, but the popup should
  // only show it once.
  const seen = new Set<string>();
  const unresolvedIssues: RsiStatusUnresolvedIssue[] = [];
  for (const sys of systems) {
    for (const issue of sys.unresolvedIssues) {
      const key = `${issue.title}|${issue.url}`;
      if (seen.has(key)) continue;
      seen.add(key);
      unresolvedIssues.push(issue);
    }
  }

  const reportedLevel = coerceLevel(parsed.summaryStatus);
  // Take the worst of the reported summary and the max per-system severity
  // — cState sometimes lags one behind the other when a component's status
  // flips between regenerations.
  let worst: RsiStatusLevel = reportedLevel;
  for (const sys of systems) {
    if (LEVEL_SEVERITY[sys.level] > LEVEL_SEVERITY[worst]) worst = sys.level;
  }

  const generatedAt = parsed.buildDate && parsed.buildTime
    ? `${parsed.buildDate}T${parsed.buildTime}Z`
    : '';

  return {
    level: worst,
    reportedLevel,
    systems,
    unresolvedIssues,
    generatedAt,
    pageUrl: `${RSI_STATUS_BASE_URL}/`,
  };
}

/**
 * True when the current level indicates a user-visible problem. `notice` is
 * informational (planned windows, courtesy messages) and not counted here
 * — the popup should keep its regular UX in that case.
 */
export function isRsiStatusIncident(level: RsiStatusLevel): boolean {
  return level === 'disrupted' || level === 'down' || level === 'maintenance';
}
